[project]
name = "meetingsnotetakingai"
version = "0.1.0"
description = ""
authors = [
    {name = "Ander Góngora",email = "andergongoraallue@gmail.com"}
]
requires-python = ">=3.13"
dependencies = [
    "PyAudioWPatch>=0.2.12.5",
    "numpy>=1.26.0",
    "openai-whisper>=20231117",
    "torch>=2.0.0",
    "google-generativeai>=0.3.0",
    "python-dotenv>=1.0.0",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
